apiVersion: v1
data:  
  ca.pem: /home/sray/certs-tls/ca.pem
  tls.crt: /home/sray/certs-tls/tls.crt
  tls.key: /home/sray/certs-tls/tls.key
kind: Secret
metadata:
  creationTimestamp: null
  name: cert-secret
  namespace: ikoplus
type: kubernetes.io/tls